// packages/mfe-vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { useCvStore } from './stores/cvStore';

const store = useCvStore();
const tab   = ref<'projects' | 'education' | 'about'>('projects');

type Tab = 'projects' | 'education' | 'about';
const TABS: Tab[] = ['projects', 'education', 'about'];

function switchTab(t: Tab) {
  tab.value = t;
  store.activeSection = t;
}

function emitAction(result: string) {
  window.dispatchEvent(new CustomEvent('cv:vue-action', { detail: { result } }));
}

// Listen for shell-dispatched actions
function handleShellVue(e: Event) {
  const { action, payload } = (e as CustomEvent<{ action: string; payload?: string }>).detail;
  store.commits += 1;

  if (action === 'setSection' && payload && TABS.includes(payload as Tab)) {
    switchTab(payload as Tab);
    emitAction(`setSection("${payload}")`);
  } else if (action === 'fetchProjects') {
    store.fetchProjects();
    emitAction('fetchProjects() → resolved [4 items]');
  } else if (action === 'broadcastEvent') {
    store.broadcastEvent();
    emitAction('broadcastEvent("mfe:update")');
  }
}

onMounted(()   => window.addEventListener('cv:shell-vue', handleShellVue));
onUnmounted(() => window.removeEventListener('cv:shell-vue', handleShellVue));
</script>

<template>
  <div class="mfe-root">

    <!-- Panel header -->
    <div class="panel-header">
      <span class="panel-title">
        <span class="panel-dot" />
        mfe-vue / src / App.vue
      </span>
      <div class="tech-badges">
        <span class="tech-badge tb-vue">Vue 3</span>
        <span class="tech-badge tb-pinia">Pinia</span>
        <span class="tech-badge tb-vite">Vite</span>
      </div>
    </div>

    <!-- Pinia store block -->
    <div class="store-block">
      <div class="store-label pinia-label">▸ pinia store state</div>
      <div class="store-row">
        <span class="store-key">activeSection</span>
        <span class="store-val section-v">{{ tab }}</span>
      </div>
      <div class="store-row">
        <span class="store-key">locale</span>
        <span class="store-val active">{{ store.locale }}</span>
      </div>
      <div class="store-row">
        <span class="store-key">mfeConnected</span>
        <span class="store-val active">true</span>
      </div>
      <div class="store-row">
        <span class="store-key">commits</span>
        <span class="store-val">{{ store.commits }}</span>
      </div>
    </div>

    <!-- Nav tabs -->
    <div class="nav-tabs">
      <button
        v-for="t in TABS"
        :key="t"
        :class="['nav-tab', tab === t ? 'active-vue' : '']"
        @click="switchTab(t)"
      >{{ t }}</button>
    </div>

    <!-- Section content -->
    <div class="cv-section">

      <!-- Projects -->
      <template v-if="tab === 'projects'">
        <div class="section-label-inner">personal projects</div>
        <div v-for="p in store.projects" :key="p.title" class="proj-item">
          <div class="proj-name">{{ p.title }}</div>
          <div class="proj-desc">{{ p.description }} <span style="font-family:'DM Mono',monospace;font-size:12px;color:#7a7890">{{ p.period }}</span></div>
          <a v-if="p.url" :href="p.url" target="_blank" rel="noopener" class="proj-link">↗ {{ p.url }}</a>
        </div>
      </template>

      <!-- Education -->
      <template v-else-if="tab === 'education'">
        <div class="section-label-inner">education</div>
        <div v-for="e in store.education" :key="e.degree" class="edu-item">
          <div class="edu-degree">{{ e.degree }}</div>
          <div class="edu-meta">{{ e.institution }} · {{ e.years }}</div>
        </div>
      </template>

      <!-- About -->
      <template v-else-if="tab === 'about'">
        <div class="section-label-inner">professional summary</div>
        <p v-for="(para, i) in store.about.paragraphs" :key="i" class="about-para">{{ para }}</p>
        <div class="open-to-chips">
          <span v-for="item in store.about.openTo" :key="item" class="open-to-chip">{{ item }}</span>
        </div>
      </template>

    </div>
  </div>
</template>

// packages/mfe-react/src/App.tsx
import { useState, useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import type { RootState } from './store';
import { setActiveSection, toggleTheme, incrementDispatches } from './store/cvSlice';
import type { Experience, SkillGroup, Contact } from './store/cvSlice';

type Tab = 'experience' | 'skills' | 'contact';
const TABS: Tab[] = ['experience', 'skills', 'contact'];
const THEMES = ['dark', 'light', 'system'];

function emit(event: string, detail?: unknown) {
  window.dispatchEvent(new CustomEvent(`cv:${event}`, { detail, bubbles: true }));
}

export default function App() {
  const dispatch = useDispatch();
  const state = useSelector((s: RootState) => s.cv);
  const [tab, setTab] = useState<Tab>('experience');

  // Listen for shell-dispatched actions
  useEffect(() => {
    const handler = (e: Event) => {
      const { action, payload } = (e as CustomEvent<{ action: string; payload?: string }>).detail;
      dispatch(incrementDispatches());

      if (action === 'SET_ACTIVE_SECTION' && payload && TABS.includes(payload as Tab)) {
        const t = payload as Tab;
        setTab(t);
        dispatch(setActiveSection(t));
        emit('react-action', { result: `SET_ACTIVE_SECTION → "${payload}"` });
      } else if (action === 'TOGGLE_THEME') {
        dispatch(toggleTheme());
        const next = THEMES[(state.themeIdx + 1) % THEMES.length];
        emit('react-action', { result: `TOGGLE_THEME → "${next}"` });
      } else if (action === 'PING_MFE') {
        emit('react-action', { result: 'PING_MFE → dispatched' });
        emit('ping-vue');
      }
    };
    window.addEventListener('cv:shell-react', handler);
    return () => window.removeEventListener('cv:shell-react', handler);
  }, [dispatch, state.themeIdx]);

  function switchTab(t: Tab) {
    setTab(t);
    dispatch(setActiveSection(t));
  }

  return (
    <div className="mfe-root">
      {/* Panel header */}
      <div className="panel-header">
        <span className="panel-title">
          <span className="panel-dot" />
          mfe-react / src / App.tsx
        </span>
        <div className="tech-badges">
          <span className="tech-badge tb-react">React 19</span>
          <span className="tech-badge tb-redux">Redux</span>
          <span className="tech-badge tb-vite">Vite</span>
        </div>
      </div>

      {/* Redux store block */}
      <div className="store-block">
        <div className="store-label redux-label">▸ redux store state</div>
        <div className="store-row">
          <span className="store-key">activeSection</span>
          <span className="store-val section-r">{tab}</span>
        </div>
        <div className="store-row">
          <span className="store-key">theme</span>
          <span className="store-val active">{state.theme}</span>
        </div>
        <div className="store-row">
          <span className="store-key">mfeConnected</span>
          <span className="store-val active">true</span>
        </div>
        <div className="store-row">
          <span className="store-key">dispatches</span>
          <span className="store-val">{state.dispatches}</span>
        </div>
      </div>

      {/* Nav tabs */}
      <div className="nav-tabs">
        {TABS.map((t) => (
          <button
            key={t}
            className={`nav-tab${tab === t ? ' active-react' : ''}`}
            onClick={() => switchTab(t)}
          >
            {t}
          </button>
        ))}
      </div>

      {/* Section content */}
      <div className="cv-section">
        {tab === 'experience' && <ExperienceSection items={state.experience} />}
        {tab === 'skills'     && <SkillsSection groups={state.skills} />}
        {tab === 'contact'    && <ContactSection data={state.contact} />}
      </div>
    </div>
  );
}

/* ─── Experience ─────────────────────────────────────────── */
function ExperienceSection({ items }: { items: Experience[] }) {
  return (
    <>
      <div className="section-label-inner">work experience</div>
      {items.map((item) => (
        <div className="exp-item" key={item.company}>
          <div className="exp-title">
            {item.role} <span className="exp-dot">·</span> {item.company}
          </div>
          <div className="exp-meta">{item.period}</div>
          <ul className="exp-bullets">
            {item.bullets.map((b, i) => <li key={i}>{b}</li>)}
          </ul>
        </div>
      ))}
    </>
  );
}

/* ─── Skills ─────────────────────────────────────────────── */
function SkillsSection({ groups }: { groups: SkillGroup[] }) {
  return (
    <>
      <div className="section-label-inner">technical skills</div>
      {groups.map((g) => (
        <div className="skill-group" key={g.category}>
          <div className="skill-group-label">{g.comment}</div>
          <div className="skill-grid">
            {g.items.map((item) => (
              <span
                key={item.label}
                className={`skill-chip${item.highlight ? ` hl-${item.highlight}` : ''}`}
              >
                {item.label}
              </span>
            ))}
          </div>
        </div>
      ))}
    </>
  );
}

/* ─── Contact ────────────────────────────────────────────── */
function ContactSection({ data }: { data: Contact }) {
  return (
    <>
      <div className="section-label-inner">contact</div>
      <div className="contact-row">
        <span className="contact-icon">@</span>
        <span>{data.email}</span>
      </div>
      <div className="contact-row">
        <span className="contact-icon">📱</span>
        <span>{data.phone}</span>
      </div>
      <div className="contact-row">
        <span className="contact-icon">in</span>
        <a href={data.linkedin} target="_blank" rel="noopener" className="contact-link">
          linkedin.com/in/fmv85
        </a>
      </div>
      <div className="contact-row">
        <span className="contact-icon">⌥</span>
        <a href={data.github} target="_blank" rel="noopener" className="contact-link">
          github.com/lfelipemarin
        </a>
      </div>
      <div className="contact-row">
        <span className="contact-icon">↗</span>
        <a href={data.portfolio} target="_blank" rel="noopener" className="contact-link">
          portfolio
        </a>
      </div>
    </>
  );
}
